2024-01-29 22:38:37,371 mainLog ERROR l:54 f:logs.py: Erro que afeta um única execução - ex: user sem permissão
